### ISSUE TITLE
从隔壁来ruoli项目来的  想问问大佬那个apple怎么搞啊   搞的头昏脑涨  没有一点儿头绪

### ISSUE THREAD

**Issue by beggerlove** [hero7069/he#1]

**Comment by hero7069** [comment]
没搞出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月13日(周日) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hero7069/he] 从隔壁来ruoli项目来的  想问问大佬那个apple怎么搞啊   搞的头昏脑涨  没有一点儿头绪 (Issue #1)
